export default {
  TOKEN_SET_TOKEN: 'TOKEN_SET_TOKEN',
  TOKEN_CLEAR_TOKEN: 'TOKEN_CLEAR_TOKEN',

  UI_SHOW_LOADING: 'UI_SHOW_LOADING',
  UI_HIDE_LOADING: 'UI_HIDE_LOADING',
  UI_SHOW_TOAST: 'UI_SHOW_TOAST',
  UI_HIDE_TOAST: 'UI_HIDE_TOAST',

  GET_SENSORS: 'GET_SENSORS',
  GET_SENSORS_STATUS: 'GET_SENSORS_STATUS',
  GET_SENSORS_DAY_DATA: 'GET_SENSORS_DAY_DATA',
}
