apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-static
data:
  azurestorageaccountkey: >-
    {{ .Values.file.key }}
  azurestorageaccountname: {{ .Values.file.name }}
type: Opaque

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "..fullname" . }}-static
spec:
  capacity:
    storage: {{ .Values.file.capacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: {{ include "..fullname" . }}-static
    shareName: {{ .Values.file.path }}
    secretNamespace: {{ .Release.Namespace }} 
    readOnly: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "..fullname" . }}-static
spec:
  resources:
    requests:
      storage: {{ .Values.file.capacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  volumeName: {{ include "..fullname" . }}-static
  