#! /bin/bash
set -e
yarn_image=node:12.22.1-alpine

docker run --rm -e "NODE_ENV=dev" -v $(pwd):/app -v /tmp/frontend_yarn:/yarn -v /tmp/frontend_modules:/app/node_modules -w /app ${yarn_image} sh test.sh
